# Generated by Django 3.2.6 on 2021-08-19 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soz',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('correct', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='H_or_X',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong', models.CharField(max_length=50)),
                ('soz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='H_va_x.soz')),
            ],
        ),
    ]
